export * from './Home';
export * from './Procesos';
export * from './Contacto';
export * from './Proyectos';
export * from './ProyectosSlug';
export * from './ServicioSlug';
export * from './Servicio';
export * from './Blog';
export * from './BlogSlug';
